from __future__ import annotations

from typing import Protocol

from cortex.domain.models import (
    Checkpoint,
    Decision,
    Message,
    Stream,
    Update,
)


# ── Terminal Adapter ─────────────────────────────────────────


class TerminalAdapter(Protocol):
    """Core operations any terminal backend must support.

    Implemented by TmuxAdapter today. Could be replaced by
    ClaudeCodeUriAdapter or similar in the future.
    """

    def pane_exists(self, pane_id: str) -> bool: ...

    def create_pane(
        self,
        cwd: str,
        shell_cmd: str,
        *,
        target_session: str | None = None,
    ) -> str | None:
        """Create a new pane. Returns pane_id or None on failure."""
        ...

    def destroy_pane(self, pane_id: str) -> bool: ...

    def capture_output(self, pane_id: str, lines: int = 50) -> str | None: ...

    def send_text(self, pane_id: str, text: str) -> bool:
        """Send text + Enter to a pane (reliable, buffered delivery)."""
        ...

    def send_keys(self, pane_id: str, keys: str) -> bool:
        """Send raw keystrokes to a pane."""
        ...

    def focus(self, pane_id: str) -> None: ...

    def wait_for_idle(self, pane_id: str, timeout: int = 30) -> bool:
        """Wait until pane shows an idle prompt (❯)."""
        ...

    def list_pane_ids(self) -> set[str]: ...

    def is_running(self) -> bool:
        """Check if the terminal backend is available."""
        ...


# ── Repository Protocols ─────────────────────────────────────


class SessionRepository(Protocol):
    def register(self, session_id: str | None, data: dict) -> dict: ...
    def get(self, session_id: str) -> dict | None: ...
    def update(self, session_id: str, data: dict, *, trigger: str = "update", actor: str | None = None) -> dict | None: ...
    def update_runtime(self, session_id: str, runtime: str, trigger: str = "health-check", actor: str | None = None) -> dict | None: ...
    def list(self, filters: dict | None = None, *, brief: bool = False, limit: int | None = None) -> list[dict]: ...
    def resolve(self, ref: str) -> dict | None: ...
    def close(self, session_id: str, trigger: str = "close", actor: str | None = None) -> dict | None: ...


class MessageRepository(Protocol):
    def create(self, sender: str, recipient: str, content: str, *, meta: dict | None = None) -> Message: ...
    def get_pending(self, recipient: str, limit: int = 10) -> list[Message]: ...
    def mark_delivered(self, message_id: str) -> None: ...
    def expire_for_session(self, session_name: str) -> int: ...


class StreamRepository(Protocol):
    def create(self, title: str, repos: list[str], *, metadata: dict | None = None) -> Stream: ...
    def get(self, stream_id: str) -> Stream | None: ...
    def list(self, status: str = "active") -> list[Stream]: ...
    def update(self, stream_id: str, **fields: object) -> Stream | None: ...
    def complete(self, stream_id: str, summary: str) -> None: ...
    def delete(self, stream_id: str) -> None: ...


class CheckpointRepository(Protocol):
    def save(self, week_of: str, content: str, stream_ids: list[str] | None = None, metadata: dict | None = None) -> Checkpoint: ...
    def get(self, week_of: str | None = None) -> Checkpoint | None: ...


class SearchRepository(Protocol):
    def text_search(self, query: str, limit: int = 20) -> list[Update | Decision | Checkpoint]: ...
    def regex_search(self, query: str, limit: int = 20) -> list[Update | Decision | Checkpoint]: ...
