from __future__ import annotations

from typing import Protocol

from cortex.domain.models import (
    Checkpoint,
    Decision,
    Message,
    Stream,
    Update,
)


# ── Terminal Adapter ─────────────────────────────────────────


class TerminalAdapter(Protocol):
    """Core operations any terminal backend must support.

    Implemented by TmuxAdapter today. Could be replaced by
    ClaudeCodeUriAdapter or similar in the future.
    """

    def pane_exists(self, pane_id: str) -> bool: ...

    def create_pane(
        self,
        cwd: str,
        shell_cmd: str,
        *,
        target_session: str | None = None,
    ) -> str | None:
        """Create a new pane running shell_cmd via fish -c. Returns pane_id or None."""
        ...

    def create_interactive_pane(
        self,
        cwd: str,
        *,
        target_session: str | None = None,
    ) -> str | None:
        """Create a new interactive pane (bare fish shell). Returns pane_id or None."""
        ...

    def destroy_pane(self, pane_id: str) -> bool: ...

    def capture_output(self, pane_id: str, lines: int = 50) -> str | None: ...

    def send_text(self, pane_id: str, text: str) -> bool:
        """Send text + Enter to a pane. For internal commands only (env setup, slash commands, /exit).
        Never use for delivering messages or prompts — use channels for that."""
        ...

    def send_keys(self, pane_id: str, keys: str) -> bool:
        """Send raw keystrokes to a pane. For internal control only (Enter to confirm dialogs)."""
        ...

    def focus(self, pane_id: str) -> None: ...

    def wait_for_idle(self, pane_id: str, timeout: int = 30) -> bool:
        """Wait until pane shows an idle prompt (❯)."""
        ...

    def list_pane_ids(self) -> set[str]: ...

    def is_running(self) -> bool:
        """Check if the terminal backend is available."""
        ...


# ── Repository Protocols ─────────────────────────────────────


class SessionRepository(Protocol):
    def register(self, session_id: str | None, data: dict) -> dict: ...
    def get(self, session_id: str) -> dict | None: ...
    def update(self, session_id: str, data: dict, *, trigger: str = "update", actor: str | None = None) -> dict | None: ...
    def update_runtime(self, session_id: str, runtime: str, trigger: str = "health-check", actor: str | None = None) -> dict | None: ...
    def list(self, filters: dict | None = None, *, brief: bool = False, limit: int | None = None, include_terminal: bool = False) -> list[dict]: ...
    def resolve(self, ref: str) -> dict | None: ...
    def close(self, session_id: str, trigger: str = "close", actor: str | None = None) -> dict | None: ...


class MessageRepository(Protocol):
    def create(self, sender: str, recipient: str, content: str, *, meta: dict | None = None) -> Message: ...
    def get_pending(self, recipient: str, limit: int = 10) -> list[Message]: ...
    def has_replies(self, *, from_session: str, to_session: str, after: str) -> bool: ...
    def mark_delivered(self, message_id: str) -> None: ...
    def expire_for_session(self, session_name: str) -> int: ...


class StreamRepository(Protocol):
    def create(self, title: str, repos: list[str], *, metadata: dict | None = None) -> Stream: ...
    def get(self, stream_id: str) -> Stream | None: ...
    def resolve(self, ref: str) -> Stream | None: ...
    def get_active(self) -> list[Stream]: ...
    def list(self, status: str = "active") -> list[Stream]: ...
    def update(self, stream_id: str, **fields: object) -> Stream | None: ...
    def complete(self, stream_id: str, summary: str) -> None: ...
    def delete(self, stream_id: str) -> None: ...
    def add_update(self, stream_id: str, content: str, summary: str, *, metadata: dict | None = None) -> Update: ...
    def edit_update(self, update_id: str, **kwargs: object) -> Update | None: ...
    def delete_update(self, update_id: str) -> None: ...
    def add_decision(self, stream_id: str, what: str, why: str, *, metadata: dict | None = None) -> Decision: ...
    def edit_decision(self, decision_id: str, **kwargs: object) -> Decision | None: ...
    def delete_decision(self, decision_id: str) -> None: ...
    def get_child_ids(self, stream_id: str) -> tuple[list[str], list[str]]: ...
    def get_update_by_id(self, update_id: str) -> Update | None: ...
    def get_decision_by_id(self, decision_id: str) -> Decision | None: ...
    def iter_all_updates(self) -> list[Update]: ...
    def iter_all_decisions(self) -> list[Decision]: ...
    def get_context(self, stream_id: str) -> dict: ...
    def get_recent_activity(self, limit: int = 50, active_only: bool = False) -> list[dict]: ...
    def link_session(self, session_id: str, stream_id: str, repo: str = "", branch: str = "") -> None: ...
    def unlink_session(self, session_id: str, stream_id: str) -> None: ...
    def move_session(self, session_id: str, from_stream_id: str, to_stream_id: str) -> None: ...
    def list_sessions(self, limit: int = 50, active_only: bool = False) -> list[dict]: ...
    def get_streams_for_session(self, session_id: str) -> list[str]: ...
    def text_search(self, query: str, limit: int = 20) -> list[Update | Decision]: ...
    def regex_search(self, query: str, limit: int = 20) -> list[Update | Decision]: ...


class CheckpointRepository(Protocol):
    def save(self, week_of: str, content: str, stream_ids: list[str] | None = None, metadata: dict | None = None) -> Checkpoint: ...
    def get(self, week_of: str | None = None) -> Checkpoint | None: ...
    def get_by_id(self, checkpoint_id: str) -> Checkpoint | None: ...
    def iter_all(self) -> list[Checkpoint]: ...
    def text_search(self, query: str, limit: int = 20) -> list[Checkpoint]: ...
    def regex_search(self, query: str, limit: int = 20) -> list[Checkpoint]: ...


class VectorStore(Protocol):
    @property
    def available(self) -> bool: ...
    def search(self, query: str, limit: int = 20) -> list[tuple[str, str, float]]: ...
    def index(self, entity_id: str, entity_type: str, stream_id: str, content: str) -> None: ...
    def deindex(self, entity_id: str) -> None: ...
    def clear(self) -> None: ...
    def rebuild(self, entries: list[tuple[str, str, str, str]]) -> None: ...
